### ISSUE TITLE
Circular ref will not be inlined.

### ISSUE THREAD

**Issue by NickNeck** [hrzndhrn/xema#127]

**Comment by pulzzejason** [comment]
I downloaded the changes you made and ran the same test I shared in [this comment](https://github.com/hrzndhrn/xema/pull/125#issuecomment-675057838).

It didn't work for me but the error message was a bit different:

```
** (KeyError) key "ServiceOrderItemRef.json" not found in: %{}
    (stdlib) :maps.get("ServiceOrderItemRef.json", %{})
    (xema) lib/xema/ref.ex:118: Xema.Ref.fetch!/3
    (xema) lib/xema/behaviour.ex:164: anonymous fn/5 in Xema.Behaviour.inline_refs/4
    (xema) lib/xema/behaviour.ex:428: anonymous fn/3 in Xema.Behaviour.map/3
    (elixir) lib/map.ex:210: Map.new_transform/3
    (xema) lib/xema/behaviour.ex:420: anonymous fn/3 in Xema.Behaviour.map/3
    (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (elixir) lib/enum.ex:1956: Enum.map/2
    (xema) lib/xema/behaviour.ex:420: Xema.Behaviour.map/3
    (xema) lib/xema/behaviour.ex:420: anonymous fn/3 in Xema.Behaviour.map/3
    (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (elixir) lib/enum.ex:1956: Enum.map/2
    (xema) lib/xema/behaviour.ex:420: Xema.Behaviour.map/3
    (xema) lib/xema/behaviour.ex:428: anonymous fn/3 in Xema.Behaviour.map/3
    (elixir) lib/map.ex:210: Map.new_transform/3
    (xema) lib/xema/behaviour.ex:420: anonymous fn/3 in Xema.Behaviour.map/3
    (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
    (stdlib) maps.erl:232: :maps.fold_1/3
```

<details>
  <summary>previous error</summary>
  
  ```
  ** (KeyError) key "OrderItemActionType.json" not found in: %{"ServiceOrderItem.json" => %JsonXema{refs: %{}, schema: %Xema.Schema{properties: %{"@baseType" => %Xema.Schema{data: %{"example" => "ResourceSpecification"}, type: :string}, "@schemaLocation" => %Xema.Schema{format: :uri, type: :string}, "@type" => %Xema.Schema{data: %{"example" => "LogicalResourceSpecification"}, type: :string}, "action" => %Xema.Schema{ref: %Xema.Ref{pointer: "OrderItemActionType.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "OrderItemActionType.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "appointment" => %Xema.Schema{ref: %Xema.Ref{pointer: "AppointmentRef.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "AppointmentRef.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "id" => %Xema.Schema{type: :string}, "quantity" => %Xema.Schema{type: :integer}, "service" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "serviceOrderItem" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceOrderItem.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceOrderItem.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceOrderItemRelationship" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceOrderItemRelationship.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceOrderItemRelationship.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "state" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceOrderItemStateType.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceOrderItemStateType.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}}, required: #MapSet<["action", "id", "service"]>, type: :map}}, "ServiceRefOrValue.json" => %JsonXema{refs: %{}, schema: %Xema.Schema{properties: %{"@baseType" => %Xema.Schema{data: %{"example" => "ResourceSpecification"}, type: :string}, "@referredType" => %Xema.Schema{type: :string}, "@schemaLocation" => %Xema.Schema{format: :uri, type: :string}, "@type" => %Xema.Schema{data: %{"example" => "LogicalResourceSpecification"}, type: :string}, "category" => %Xema.Schema{type: :string}, "description" => %Xema.Schema{type: :string}, "endDate" => %Xema.Schema{format: :date_time, type: :string}, "feature" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Feature.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Feature.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "hasStarted" => %Xema.Schema{type: :boolean}, "href" => %Xema.Schema{type: :string}, "id" => %Xema.Schema{type: :string}, "isBundle" => %Xema.Schema{type: :boolean}, "isServiceEnabled" => %Xema.Schema{type: :boolean}, "isStateful" => %Xema.Schema{type: :boolean}, "name" => %Xema.Schema{type: :string}, "note" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Note.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Note.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "place" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedPlaceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedPlaceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "relatedEntity" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedEntityRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedEntityRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "relatedParty" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedParty.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedParty.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceCharacteristic" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Characteristic.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Characteristic.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceDate" => %Xema.Schema{type: :string}, "serviceOrderItem" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedServiceOrderItem.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedServiceOrderItem.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceRelationship" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRelationship.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRelationship.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceSpecification" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceSpecificationRef.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceSpecificationRef.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "serviceType" => %Xema.Schema{type: :string}, "startDate" => %Xema.Schema{format: :date_time, type: :string}, "startMode" => %Xema.Schema{type: :string}, "state" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceStateType.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceStateType.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "supportingResource" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ResourceRef.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ResourceRef.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "supportingService" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}}, type: :map}}, "ServiceRelationship.json" => %JsonXema{refs: %{}, schema: %Xema.Schema{properties: %{"@baseType" => %Xema.Schema{type: :string}, "@schemaLocation" => %Xema.Schema{format: :uri, type: :string}, "@type" => %Xema.Schema{type: :string}, "relationshipType" => %Xema.Schema{type: :string}, "service" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "serviceRelationshipCharacteristic" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Characteristic.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Characteristic.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}}, required: #MapSet<["relationshipType"]>, type: :map}}}
  (stdlib) :maps.get("OrderItemActionType.json", %{"ServiceOrderItem.json" => %JsonXema{refs: %{}, schema: %Xema.Schema{properties: %{"@baseType" => %Xema.Schema{data: %{"example" => "ResourceSpecification"}, type: :string}, "@schemaLocation" => %Xema.Schema{format: :uri, type: :string}, "@type" => %Xema.Schema{data: %{"example" => "LogicalResourceSpecification"}, type: :string}, "action" => %Xema.Schema{ref: %Xema.Ref{pointer: "OrderItemActionType.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "OrderItemActionType.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "appointment" => %Xema.Schema{ref: %Xema.Ref{pointer: "AppointmentRef.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "AppointmentRef.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "id" => %Xema.Schema{type: :string}, "quantity" => %Xema.Schema{type: :integer}, "service" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "serviceOrderItem" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceOrderItem.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceOrderItem.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceOrderItemRelationship" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceOrderItemRelationship.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceOrderItemRelationship.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "state" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceOrderItemStateType.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceOrderItemStateType.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}}, required: #MapSet<["action", "id", "service"]>, type: :map}}, "ServiceRefOrValue.json" => %JsonXema{refs: %{}, schema: %Xema.Schema{properties: %{"@baseType" => %Xema.Schema{data: %{"example" => "ResourceSpecification"}, type: :string}, "@referredType" => %Xema.Schema{type: :string}, "@schemaLocation" => %Xema.Schema{format: :uri, type: :string}, "@type" => %Xema.Schema{data: %{"example" => "LogicalResourceSpecification"}, type: :string}, "category" => %Xema.Schema{type: :string}, "description" => %Xema.Schema{type: :string}, "endDate" => %Xema.Schema{format: :date_time, type: :string}, "feature" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Feature.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Feature.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "hasStarted" => %Xema.Schema{type: :boolean}, "href" => %Xema.Schema{type: :string}, "id" => %Xema.Schema{type: :string}, "isBundle" => %Xema.Schema{type: :boolean}, "isServiceEnabled" => %Xema.Schema{type: :boolean}, "isStateful" => %Xema.Schema{type: :boolean}, "name" => %Xema.Schema{type: :string}, "note" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Note.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Note.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "place" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedPlaceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedPlaceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "relatedEntity" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedEntityRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedEntityRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "relatedParty" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedParty.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedParty.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceCharacteristic" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Characteristic.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Characteristic.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceDate" => %Xema.Schema{type: :string}, "serviceOrderItem" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "RelatedServiceOrderItem.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "RelatedServiceOrderItem.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceRelationship" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRelationship.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRelationship.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "serviceSpecification" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceSpecificationRef.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceSpecificationRef.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "serviceType" => %Xema.Schema{type: :string}, "startDate" => %Xema.Schema{format: :date_time, type: :string}, "startMode" => %Xema.Schema{type: :string}, "state" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceStateType.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceStateType.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "supportingResource" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ResourceRef.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ResourceRef.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}, "supportingService" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}}, type: :map}}, "ServiceRelationship.json" => %JsonXema{refs: %{}, schema: %Xema.Schema{properties: %{"@baseType" => %Xema.Schema{type: :string}, "@schemaLocation" => %Xema.Schema{format: :uri, type: :string}, "@type" => %Xema.Schema{type: :string}, "relationshipType" => %Xema.Schema{type: :string}, "service" => %Xema.Schema{ref: %Xema.Ref{pointer: "ServiceRefOrValue.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "ServiceRefOrValue.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, "serviceRelationshipCharacteristic" => %Xema.Schema{items: %Xema.Schema{ref: %Xema.Ref{pointer: "Characteristic.json", uri: %URI{authority: nil, fragment: nil, host: nil, path: "Characteristic.json", port: nil, query: nil, scheme: nil, userinfo: nil}}}, type: :list}}, required: #MapSet<["relationshipType"]>, type: :map}}})
  (xema) lib/xema/ref.ex:118: Xema.Ref.fetch!/3
  (xema) lib/xema/ref.ex:97: Xema.Ref.validate/3
  (xema) lib/xema/validator.ex:82: Xema.Validator.do_properties/4
  (xema) lib/xema/validator.ex:139: Xema.Validator.validate_by/4
  (xema) lib/xema/validator.ex:87: Xema.Validator.validate/3
  (xema) lib/xema/validator.ex:82: Xema.Validator.items_list/4
  (xema) lib/xema/validator.ex:121: Xema.Validator.validate_by/4
  (xema) lib/xema/validator.ex:87: Xema.Validator.do_properties/4
  (xema) lib/xema/validator.ex:139: Xema.Validator.validate_by/4
  (xema) lib/xema/validator.ex:87: Xema.Validator.validate/3
  (json_xema) lib/json_xema.ex:6: JsonXema.validate/3
  (json_xema) lib/json_xema.ex:6: JsonXema.valid?/2
  ```
</details>

I also confirmed that the recent changes were pulled in my `deps` folder for both Xema and JsonXema.

**Comment by NickNeck** [comment]
I'm sorry about that. I will take another look today.

**Comment by NickNeck** [comment]
Hello @pulzzejason, if you'd be so kind as to try again. This time only `Xema` was updated.

**Comment by pulzzejason** [comment]
@NickNeck Just checked with the latest and it looks good! Will continue to use it and let you know if I run into any issues. Thanks!
