### ISSUE TITLE
Cannot combine and cast Xemas in single-type lists

### ISSUE THREAD

**Issue by smoes** [hrzndhrn/xema#134]
The following schema works depending on what we are doing with it:
```
schema = Xema.new({:list, items: Xema.new(:string)})

# happily returns :ok      
Xema.validate(schema, ["hello", "world"])  

# crashes in agony      
Xema.cast(schema, ["hello", "world"])  
      
          
```
The following schema works fine for validating as well as casting:

```
schema = Xema.new({:list, items: :string})
```

However, how are we supposed to combine existing Xemas into a list? Is this a bug? 

---
Xema version: 0.13.1
Stacktrace of crash when casting:

```
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for %Xema{refs: %{}, schema: %Xema.Schema{type: :string}} of type Xema (a struct)
     code: Xema.cast(schema, ["hello", "world"]))
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:193: Enumerable.slice/1
       (elixir) lib/enum.ex:3083: Enum.slice_any/3
       (elixir) lib/enum.ex:398: Enum.at/3
       (xema) lib/xema.ex:916: anonymous fn/6 in Xema.cast_values_list/4
       (elixir) lib/enum.ex:3325: Enumerable.List.reduce/3
       (elixir) lib/enum.ex:1998: Enum.reduce_while/3
       (xema) lib/xema.ex:915: Xema.cast_values_list/4
       (xema) lib/xema.ex:729: Xema.do_cast/4
       (xema) lib/xema.ex:706: Xema.cast/3

```

**Comment by smoes** [comment]
I just noticed that the following schema works for cast:
```
schema = Xema.new({:list, items: [Xema.new(:string)]})
```

Why does `:string` not need a list, while a Xema needs one?

**Comment by NickNeck** [comment]
Yes, that is a bug. The schema of your first post should do the sam as this one:
```elixir
iex(1)> schema = Xema.new({:list, items: :string})
%Xema{
  refs: %{},
  schema: %Xema.Schema{items: %Xema.Schema{type: :string}, type: :list}
}
iex(2)> Xema.validate(schema, ["hello", "world"])
:ok
iex(3)> Xema.cast(schema, ["hello", "world"])
{:ok, ["hello", "world"]}
iex(4)> Xema.cast(schema, [:hello, :world])
{:ok, ["hello", "world"]}
iex(5)>
```

In general every sub-schema like `:string`, `{:string, min_length: 2}` can be replaced by an `Xema`.
```elixir
iex(1)> str = Xema.new({:string, min_length: 3})
%Xema{refs: %{}, schema: %Xema.Schema{min_length: 3, type: :string}}
iex(2)> schema = Xema.new(properties: %{
...(2)>   s1: {:string, min_length: 3},
...(2)>   s2: str
...(2)> })
%Xema{
  refs: %{},
  schema: %Xema.Schema{
    properties: %{
      s1: %Xema.Schema{min_length: 3, type: :string},
      s2: %Xema.Schema{min_length: 3, type: :string}
    }
  }
}
```

In your second example the schema for the `:items` will just check the first item because the list contains just a sub-schema for the first item. Every additional item will not be validated.
```
Xema.new({:list, items: :string}) # => all items in the list must be of type string 
Xema.new({:list, items: [:string, :integer]}) # => the first item must be a string, the second item must be an integer, every additional item can be from any type
```

See also [Structuring a schema](https://hexdocs.pm/xema/usage.html#structuring-a-schema) in the docs.

Thanks for reporting this. I will take a look at the next days and fix that bug.

**Comment by smoes** [comment]
Wow, that was fast :) Thank you very much, keep up the good work!
