### ISSUE TITLE
Xema loader is not being called, can't resolve references

### ISSUE THREAD

**Issue by doorgan** [hrzndhrn/xema#172]
I'm trying to use `Xema` to build validations(and some other code generation) from a json schema document, I was experimenting with it but apparently the loader is never called.

Below is the livebook I've been using to test this. Is there something I'm doing wrong here?

---

```elixir
Mix.install(
  [:xema, :rexbug],
  config: [
    xema: [
      loader: JsonXemaLoader
    ]
  ]
)
```

```
Resolving Hex dependencies...
Resolution completed in 0.414s
New:
  conv_case 0.2.3
  redbug 1.2.2
  rexbug 1.0.6
  xema 0.17.0
* Getting xema (Hex package)
* Getting rexbug (Hex package)
* Getting redbug (Hex package)
* Getting conv_case (Hex package)
===> Fetching rebar3_hex v7.0.2
===> Fetching hex_core v0.8.4
===> Fetching verl v1.1.1
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
===> Analyzing applications...
===> Compiling redbug
==> rexbug
Compiling 4 files (.ex)
Generated rexbug app
==> conv_case
Compiling 1 file (.ex)
Generated conv_case app
==> xema
Compiling 19 files (.ex)
Generated xema app
```

```
:ok
```

## Section

```elixir
defmodule JsonXemaLoader do
  @moduledoc false

  @behaviour Xema.Loader

  @spec fetch(binary) :: {:ok, map} | {:error, any}
  def fetch(uri) do
    IO.inspect(uri, label: "loader uri")

    schema = %{
      "definitions" => %{
        "AddElementPayload" => %{
          "additionalProperties" => false,
          "properties" => %{
            "elements" => %{"items" => %{"$ref" => "#/definitions/Element"}, "type" => "array"},
            "isBroadcaster" => %{"type" => "boolean"}
          },
          "required" => ["elements"],
          "type" => "object"
        },
        "DefWithUnion" => %{
          "properties" => %{
            "value" => %{"anyOf" => [%{"$ref" => "#/definitions/Element"}, "string"]}
          },
          "type" => "object"
        },
        "Element" => %{
          "additionalProperties" => false,
          "properties" => %{"author" => %{"type" => "object"}, "id" => %{"type" => "string"}},
          "required" => ["id", "author"]
        },
        "SomeArray" => %{"type" => "array"},
        "SomethingUsingArray" => %{
          "properties" => %{"foo" => %{"$ref" => "#/definitions/SomeArray"}}
        },
        "UpdatePayload" => %{
          "additionalProperties" => false,
          "properties" => %{
            "clearTransientSessionId" => %{"type" => "string"},
            "elements" => %{"items" => %{"$ref" => "#/definitions/Element"}, "type" => "array"},
            "isBroadcaster" => %{"type" => "boolean"}
          },
          "required" => ["elements"],
          "type" => "object"
        }
      }
    }

    {:ok, schema}
  end
end
```

```
{:module, JsonXemaLoader, <<70, 79, 82, 49, 0, 0, 9, ...>>, {:fetch, 1}}
```

```elixir
Rexbug.start("Xema.Loader :: return")

Xema.from_json_schema(
  %{
    "additionalProperties" => false,
    "properties" => %{
      "elements" => %{"items" => %{"$ref" => "#/definitions/Element"}, "type" => "array"},
      "isBroadcaster" => %{"type" => "boolean"}
    },
    "required" => ["elements"],
    "type" => "object"
  },
  loader: JsonXemaLoader
)
```

```
** (Xema.SchemaError) Ref #/definitions/Element not found.
    (xema 0.17.0) lib/xema/schema.ex:319: Xema.Schema.fetch!/2
    (xema 0.17.0) lib/xema/behaviour.ex:292: anonymous fn/2 in Xema.Behaviour.get_schema_refs/2
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.2) lib/enum.ex:1552: Enum.into/3
    (xema 0.17.0) lib/xema/behaviour.ex:269: anonymous fn/3 in Xema.Behaviour.update_master_refs/2
    (elixir 1.14.2) lib/map.ex:883: Map.update!/3
    (xema 0.17.0) lib/xema/behaviour.ex:153: Xema.Behaviour.update_refs/2
    #cell:g7zetdkudgoeintpy4iksrtskfuo5r25:3: (file)
```
```
redbug done, timeout - 0
```

**Comment by doorgan** [comment]
I see the loader is called if the reference is a path uri, not a reference to the same document, so for instance `root.schema/definitions/Element` will trigger the loader

My goal is to define a `%Xema{}` for each definition in the json schema, not to define a single `%Xema{}` for the whole document

In any case this library is awesome, I'm just a bit stuck on this but otherwise you have very good stuff here!

**Comment by doorgan** [comment]
Welp, turns out you have it all figured out and it was just me being a dummy, I can achieve what I want with this:

```elixir
schema = %{
  "definitions" => %{
    "AddElementPayload" => %{
      "additionalProperties" => false,
      "properties" => %{
        "elements" => %{"items" => %{"$ref" => "#/definitions/Element"}, "type" => "array"},
        "isBroadcaster" => %{"type" => "boolean"}
      },
      "required" => ["elements"],
      "type" => "object"
    },
    "DefWithUnion" => %{
      "properties" => %{
        "value" => %{"anyOf" => [%{"$ref" => "#/definitions/Element"}, %{"type" => "string"}]}
      },
      "type" => "object"
    },
    "Element" => %{
      "title" => "Element",
      "additionalProperties" => false,
      "properties" => %{"author" => %{"type" => "object"}, "id" => %{"type" => "string"}},
      "required" => ["id", "author"]
    },
    "SomeArray" => %{"type" => "array"},
    "SomethingUsingArray" => %{
      "properties" => %{"foo" => %{"$ref" => "#/definitions/SomeArray"}}
    },
    "UpdatePayload" => %{
      "additionalProperties" => false,
      "properties" => %{
        "clearTransientSessionId" => %{"type" => "string"},
        "elements" => %{"items" => %{"$ref" => "#/definitions/Element"}, "type" => "array"},
        "isBroadcaster" => %{"type" => "boolean"}
      },
      "required" => ["elements"],
      "type" => "object"
    }
  },
  "messages" => %{
    "add_element" => %{
      "payload" => %{"$ref" => "#/definitions/AddElementPayload"},
      "response" => %{"type" => "string"}
    }
  },
  "notifications" => %{
    "export_ready" => %{"type" => "string"}
  }
}

xema = Xema.from_json_schema(schema, draft: "draft7", atom: :force)

element_schema = Xema.Schema.fetch!(xema.schema, "definitions/Element")

Xema.cast(element_schema, %{})
```
```
{:error,
 %Xema.CastError{
   message: nil,
   path: [],
   required: ["author", "id"],
   to: :any,
   value: %{},
   key: nil,
   error: nil
 }}
```

Awesome work, really!
